### PR TITLE
Update packages for consistency

### PR DESCRIPTION
**Pull request by MuhammedZakir**
Currently, there is no consistency between pages. This PR is mainly for fixing it.

Some questions -
1. Is there any need for 'Installation' section? Installation command is already there at the top and there is also dependency section. IMHO, there is no need for this section.
2. External packages' installation command does not have `--external` flag. Is this deliberate?

Note: Public IP (aka espanso-package-ip) works on macOS only if `ANY` is removed from the command. I presume removing it won't create any problem in Linux either -- https://www.cyberciti.biz/faq/how-to-find-my-public-ip-address-from-command-line-on-a-linux/. Update that package maybe? I can make a PR if you are okay with this.

### CODE REVIEW

**Comment by MuhammedZakir** [comment]
Sorry for the late response! I need your opinion on table headers.

1. Replace & With

| Replace    | With                                                  |
| -------------- | ------------------------------------------------------------ |
| `:sharewifi`   | Wi-Fi password.                                       |
| `:qrsharewifi` | Wi-Fi Network config QR Code for Android and iOS 11+. |
| `:vsharewifi`  | SSID and Password.                      |

2. Trigger & Replace with

| Trigger    | Replace with                                              |
| -------------- | ------------------------------------------------------------ |
| `:sharewifi`   |  Wi-Fi password.                                       |
| `:qrsharewifi` |  Wi-Fi Network config QR Code for Android and iOS 11+. |
| `:vsharewifi`  |  SSID and Password.                    |

3. Use a header according to the package.

| Replacement    | Description                                                  |
| -------------- | ------------------------------------------------------------ |
| `:sharewifi`   | Prints Wi-Fi password.                                       |
| `:qrsharewifi` | Prints Wi-Fi Network config QR Code for Android and iOS 11+. |
| `:vsharewifi`  | Verbose output. Prints SSID and Password.                    |

**Comment by federico-terzi** [comment]
@MuhammedZakir Sorry for the late reply! Those READMEs are chosen by the package author, so I'm not really sure whether changing them could be beneficial. For example, if they update their package README, we would have to apply all the changes back to the repo

**Comment by MuhammedZakir** [comment]
I'm really sorry! Lot of things keep coming up! -_-

Is this okay? Any suggestions? Do say if I need to change something. :-)

**Comment by MuhammedZakir** [comment]
ping @federico-terzi  😀

**Comment by federico-terzi** [comment]
Hey @MuhammedZakir,
Thank you for the effort, I really appreciate it!
That said, I'm planning to refactor the espanso hub in a few months, so I'll need to change everything again...
I don't think I will be able to merge this PR anytime soon, but I'll make sure to consider your changes in the next version :)

I hope you will understand

**Comment by MuhammedZakir** [comment]
> Hey @MuhammedZakir,
> Thank you for the effort, I really appreciate it!

You're welcome! 😄 

> That said, I'm planning to refactor the espanso hub in a few months, so I'll need to change everything again...
> I don't think I will be able to merge this PR anytime soon, but I'll make sure to consider your changes in the next version :)
> 
> I hope you will understand

It's okay! After all, we are trying to make this better! If you need any help, feel free to ping me. :-)

**Comment by federico-terzi** [comment]
@MuhammedZakir I will! Thanks again :)

**Pull request closed without merging**
